config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

resources :companies

resources :industries

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_and_belongs_to_many :industries

end

app/models/industry.rb
class Industry < ActiveRecord::Base

  has_and_belongs_to_many :companies

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

def index
  @companies = Company.all
  @industries = Industry.all
  @industry = Industry.new
end

def new
  @company = Company.new
  @industries = Industry.all
  @industry = Industry.new
end

def create
  params[:company][:industry_ids] ||= []
  @company = Company.new(company_params)
  if @company.save
    redirect_to company_path(@company), notice: "Company was created successfully!"
  else
    render :new
  end
end

def update
  params[:company][:industry_ids] ||= []
  @company = Company.find(params[:id])
  if @company.update(company_params)
    redirect_to companies_path, notice: "Company was updated successfully!"
  end
end

def destroy
  @company = Company.find(params[:id])

  @company.destroy
  redirect_to companies_path, notice: "Company was deleted!"
end

def edit
  @company = Company.find(params[:id])
end

def show
@company = Company.find(params[:id])
@companies = Company.all
end


private
def company_params
  params.require(:company).permit(:name, :description, :price, :created_at, :updated_at, :industry_ids =>[])
end

def industry_params
  params.require(:industry).permit(:name, :description, :created_at, :updated_at, :company_ids => [])
end


end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController

def index
  @industries = Industry.all
  @companies = Company.all
  @company = Company.new
end

def new
  @industry = Industry.new
  @companies = Company.all
  @company = Company.new

end

def create
  params[:industry][:company_ids] ||= []
  @industry = Industry.new(industry_params)
  if @industry.save
    redirect_to industry_path(@industry), notice: "Industry was created successfully!"
  else
    render :new
  end
end

def update
  params[:industry][:company_ids] ||= []
  @industry = Industry.find(params[:id])
  if @industry.update(industry_params)
    redirect_to industries_path, notice: "Industry was updated successfully!"
  end
end

def destroy
  @industry = Industry.find(params[:id])
  @industry.destroy
  redirect_to industries_path, notice: "Industry was deleted!"
end

def edit
  @industry = Industry.find(params[:id])
end

def show
@industry = Industry.find(params[:id])
end


private
def industry_params
  params.require(:industry).permit(:name, :description, :created_at, :updated_at, :company_ids => [])
end

def company_params
  params.require(:company).permit(:name, :description, :price, :created_at, :updated_at, :industry_ids =>[])
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.label :price %>
<%= f.number_field :price %>


<% for industry in Industry.all %>
           <div>
               <%= check_box_tag "company[industry_ids][]", industry.id, @company.industries.include?(industry) %>
               <%= industry.name %>
           </div>
       <% end %>

<%= f.submit %>
<% end %>

app/views/companies/edit.html.erb
<h1> Edit <%= @company.name %> </h1>

<%= render 'form'  %>

app/views/companies/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Companies</h1>

<%= link_to "Create a New Company", new_company_path %>
<table>
  <thead>
    <tr>
      <th>
        Company Name
      </th>
      <th>
        Price
      </th>
      <th>
        Created At
      </th>
      <th>
        Updated At
      </th>
      <th>
        Industries Apart Of
      </th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td>
        <%= link_to company.name, company_path(company) %>
      </td>
      <td>
        $<%= company.price  %>
      </td>
      <td>
        <%= company.created_at %>
      </td>
      <td>
        <%= company.updated_at  %>
      </td>
      <td>
        <% company.industries.each do |industry| %>
            <%=  industry.name %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1> Add a New Company </h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Show Page for <%= @company.name %>  </h1>

<div> <%= link_to "Edit Company", edit_company_path(@company) %> </div>
<div> <%= link_to "Delete Company", company_path(@company), data: { confirm: 'Are you sure?'}, :method => :delete %> </div>

<p><strong>Name:</strong> <%= @company.name %> </p>
<p><strong>Description:</strong> <%= @company.description %> </p>
<p><strong>Price:</strong> $<%= @company.price %> </p>
<p><strong>Created At:</strong> <%= @company.created_at %></p>
<p><strong>Updated At: </strong> <%= @company.updated_at %></p>
<table>
  <thead>
    <tr>
      <th>
        Industries Apart Of:
      </th>
    </tr>
  </thead>
  <tbody>
    <% @company.industries.each do |industry| %>
    <tr>
      <td>
        <%=  industry.name %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/industries/_form.html.erb
<%= form_for @industry do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>



<%= f.label :description %>
<%= f.text_area :description %>


<% for company in Company.all %>
           <div>
               <%= check_box_tag "industry[company_ids][]", company.id, @industry.companies.include?(company) %>
               <%= company.name %>
           </div>
       <% end %>



<%= f.submit %>

<% end %>

app/views/industries/edit.html.erb
<h1> Edit <%= @industry.name %> </h1>

<%= render 'form'  %>

app/views/industries/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Industries</h1>

<%= link_to "Create a New Industry", new_industry_path %>

<table>
  <thead>
    <tr>
      <th>
        Industry Name
      </th>
      <th>
        Created At
      </th>
      <th>
        Updated At
      </th>
      <th>
        Companies in Industry
      </th>
    </tr>
  </thead>
  <tbody>
    <% @industries.each do |industry| %>
    <tr>
      <td>
        <%= link_to industry.name, industry_path(industry) %>
      </td>
      <td>
        <%= industry.created_at  %>
      </td>
      <td>
        <%= industry.updated_at  %>
      </td>
      <td>
        <% industry.companies.each do |company| %>
            <%=  company.name %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/industries/new.html.erb
<h1> Add a New Industry </h1>

<%= render 'form' %>

app/views/industries/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Show Page for the <%= @industry.name %> Industry </h1>

<div> <%= link_to "Edit Industry", edit_industry_path(@industry) %> </div>
<div> <%= link_to "Delete Company", industry_path(@industry), data: { confirm: 'Are you sure?'}, :method => :delete %> </div>

<p><strong>Name:</strong> <%= @industry.name %> </p>
<p><strong>Description:</strong> <%= @industry.description %> </p>
<p><strong>Created At:</strong> <%= @industry.created_at %></p>
<p><strong>Updated At: </strong> <%= @industry.updated_at %></p>
<table>
  <thead>
    <tr>
      <th>
        Companies in Industry
      </th>
    </tr>
  </thead>
  <tbody>
    <% @industry.companies.each do |company| %>
    <tr>
      <td>
        <%=  company.name %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>G6Assessment2Hb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p> <%= link_to "Industries Index", industries_path  %> </p>

<p> <%= link_to "Companies Index", companies_path %> </p>